" Sets how many lines of history VIM has to remember
set history=700

" Visually wrap lines
set wrap

" Set to auto read when a file is changed from the outside
set autoread

" Set 7 lines to the cursor - when moving vertically using j/k
set so=7

" When 'ignorecase' and 'smartcase' are both on, if a pattern contains an uppercase letter, it is case sensitive, otherwise, it is not.
set ignorecase
set smartcase

" Highlight search results
set hlsearch

" Show matching brackets when text indicator is over them
set showmatch

" Display Line Numbers
set number

" Use spaces instead of tabs
set expandtab

" 1 tab == 4 spaces
set shiftwidth=3
set tabstop=3

" Colors
let base16colorspace=256
syntax on
set background=dark
colorscheme base16-default

" Display tabs
set list
set listchars=tab:•\ ,trail:•,extends:»,precedes:«

" Airline Config
set laststatus=2
set t_Co=256
let g:airline#extensions#tabline#enabled = 1

" Execute pathogen
execute pathogen#infect()
