" Sets how many lines of history VIM has to remember
set history=700

" Visually wrap lines
set wrap

" Set to auto read when a file is changed from the outside
set autoread

" Set 7 lines to the cursor - when moving vertically using j/k
set so=7

" When 'ignorecase' and 'smartcase' are both on, if a pattern contains an uppercase letter, it is case sensitive, otherwise, it is not.
set ignorecase
set smartcase

set ruler

" Don't redraw while executing macros (good performance config)
set lazyredraw

" Highlight search results
set hlsearch

" Show matching brackets when text indicator is over them
set showmatch

" Display Line Numbers
set number

" Use spaces instead of tabs
set expandtab
set smarttab
set ai " Auto indent
set si " Smart indent

" 1 tab == 3 spaces
set shiftwidth=3
set tabstop=3

" Access colors present in 256 colorspace
syntax on
set background=dark
if filereadable(expand("~/.vimrc_background"))
   let base16colorspace=256
   source ~/.vimrc_background
endif

" Display tabs
set list
set listchars=tab:•\ ,trail:•,extends:»,precedes:«

" Enable pathogen autoload
execute pathogen#infect()

" Airline Config
set laststatus=2
set t_Co=256
let g:airline#extensions#tabline#enabled = 1

" Syntastic Config
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
