" Sets how many lines of history VIM has to remember
set history=700

" Visually wrap lines
set wrap

" Set to auto read when a file is changed from the outside
set autoread

" Set 7 lines to the cursor - when moving vertically using j/k
set so=7

" When 'ignorecase' and 'smartcase' are both on, if a pattern contains an uppercase letter, it is case sensitive, otherwise, it is not.
set ignorecase
set smartcase

set ruler

" Don't redraw while executing macros (good performance config)
set lazyredraw

" Highlight search results
set hlsearch

" Show matching brackets when text indicator is over them
set showmatch

" Display Line Numbers
set number

" Use spaces instead of tabs
set expandtab
set smarttab
set ai " Auto indent
set si " Smart indent

" 1 tab == 3 spaces
set shiftwidth=3
set tabstop=3

" Display tabs
set list
set listchars=tab:•\ ,trail:•,extends:»,precedes:«

" Access colors present in 256 colorspace
syntax on
set background=dark
if filereadable(expand("~/.vimrc_background"))
   let base16colorspace=256
   source ~/.vimrc_background
endif

" install/load plugins
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
Plug 'airblade/vim-gitgutter'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'itchyny/lightline.vim'
Plug 'daviesjamie/vim-base16-lightline'
call plug#end()

" vimtex
let g:vimtex_view_method = 'mupdf'

" lightline
set laststatus=2
set noshowmode
let g:lightline = {'colorscheme': 'base16'}
