# !/bin/sh

# refresh .Xresources
[[ -f $HOME/.Xresources ]] && xrdb -merge $HOME/.Xresources
[[ -f $HOME/.Xmodmap ]] && xmodmap $HOME/.Xmodmap

# enable custom keybindings configured in ~/.xbindkeysrc
xbindkeys

# start ssh-agent to make ~./ssh keys available
eval $(ssh-agent)

# start dbus-daemon to automount removable devices
if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
    eval `dbus-launch --sh-syntax --exit-with-session`
fi

# execute redshift
redshift -l 47.22:8.33 &> /dev/null &

# set wallpaper
feh --bg-scale "$HOME"'/.i3/wallpaper.png'

# execute window manager, make sure automount works
exec bash -c 'devmon -g & i3'

# when debugging i3 uncomment this line
# exec i3 -V >> ~/.i3/log 2>&1
