# !/bin/sh

[[ -f $HOME/.Xresources ]] && xrdb -merge $HOME/.Xresources
[[ -f $HOME/.Xmodmap ]] && xmodmap $HOME/.Xmodmap

# enable custom keybindings configured in ~/.xbindkeysrc
xbindkeys

# start dbus-daemon to automount removable devices
if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
    eval `dbus-launch --sh-syntax --exit-with-session`
fi

# set wallpaper
eval $(cat $HOME/.fehbg)

# execute xflux
xflux -l 47.4 -g 8.5 -k 3000

# execute window manager, make sure automount works
feh --bg-scale "$HOME"'/.i3/wallpaper.png'
exec bash -c 'devmon -g & i3'

# when debugging i3 uncomment this line
# exec i3 -V >> ~/.i3/log 2>&1
